# -*- coding: utf-8 -*-
"""FMNIST_Classification_FC_CNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z6JLfvhAATR8-fNg42QROnPM803lBqR5
"""

import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

# Make sure we're using TensorFlow 2.x in eager mode
print("TensorFlow version:", tf.__version__)

# ===============================
# 1. Load and preprocess MNIST
# ===============================
#fmnist = tf.keras.datasets.fashion_mnis
# MNIST has 60,000 training and 10,000 test images of size 28x28 (grayscale).
# Keras will automatically download it the first time you call this.
#Use Fashion instead of digits
(x_train_full, y_train_full), (x_test, y_test) = tf.keras.datasets.fashion_mnist.load_data()

print("Original training set shape:", x_train_full.shape, y_train_full.shape)
print("Original test set shape:", x_test.shape, y_test.shape)

# -------------------------------------------------
# Normalize images to [0, 1] by dividing by 255.0
# -------------------------------------------------
x_train_full = x_train_full.astype("float32") / 255.0
x_test = x_test.astype("float32") / 255.0

# ---------------------------------------
# Create a validation split from training
# ---------------------------------------
# We'll use 50,000 images for training and 10,000 for validation.
x_train, x_val = x_train_full[:50000], x_train_full[50000:]
y_train, y_val = y_train_full[:50000], y_train_full[50000:]

print("Training set:", x_train.shape, y_train.shape)
print("Validation set:", x_val.shape, y_val.shape)
print("Test set:", x_test.shape, y_test.shape)

# ==============================================
# Prepare data for the fully connected network
# ==============================================

# Flatten images to vectors of length 784 = 28*28
x_train_flat = x_train.reshape(-1, 28 * 28)
x_val_flat = x_val.reshape(-1, 28 * 28)
x_test_flat = x_test.reshape(-1, 28 * 28)

print("Flattened training set shape:", x_train_flat.shape)

# ==============================================
# Prepare data for the CNN
# ==============================================

# Add a channel dimension to each image so the shape is (28, 28, 1)
x_train_cnn = x_train[..., tf.newaxis]
x_val_cnn = x_val[..., tf.newaxis]
x_test_cnn = x_test[..., tf.newaxis]

print("CNN training data shape:", x_train_cnn.shape)

# ==============================================
# Build tf.data.Datasets for efficient iteration
# ==============================================

batch_size = 128

# Datasets for fully connected network
train_ds_fc = tf.data.Dataset.from_tensor_slices((x_train_flat, y_train)).shuffle(10000).batch(batch_size)
val_ds_fc   = tf.data.Dataset.from_tensor_slices((x_val_flat, y_val)).batch(batch_size)
test_ds_fc  = tf.data.Dataset.from_tensor_slices((x_test_flat, y_test)).batch(batch_size)

# Datasets for CNN
train_ds_cnn = tf.data.Dataset.from_tensor_slices((x_train_cnn, y_train)).shuffle(10000).batch(batch_size)
val_ds_cnn   = tf.data.Dataset.from_tensor_slices((x_val_cnn, y_val)).batch(batch_size)
test_ds_cnn  = tf.data.Dataset.from_tensor_slices((x_test_cnn, y_test)).batch(batch_size)

# ==============================================
# Shared helper: accuracy computation
# ==============================================

def accuracy_from_probs(probs, labels):
    # Compute accuracy from predicted probabilities and true labels.
    preds = tf.argmax(probs, axis=1, output_type=tf.int32)
    labels = tf.cast(labels, tf.int32)
    correct = tf.equal(preds, labels)
    return tf.reduce_mean(tf.cast(correct, tf.float32))

# ===============================================
# 2. Fully Connected Network definition
#    Architecture: 784 -> 512 -> 512 -> 10
# ===============================================

fc_model = tf.keras.Sequential(
    [
        # Input: vectors of length 784
        tf.keras.layers.Input(shape=(784,), name="input_flattened"),

        # First hidden dense layer with 512 units and ReLU activation
        tf.keras.layers.Dense(512, activation="relu", name="dense_1"),

        # Second hidden dense layer with 512 units and ReLU activation
        tf.keras.layers.Dense(512, activation="relu", name="dense_2"),

        # Output layer with 10 units (one per digit class) and Softmax
        # Softmax converts logits to a probability distribution over classes.
        tf.keras.layers.Dense(10, activation="softmax", name="output_softmax"),
    ],
    name="FullyConnectedMNIST",
)

fc_model.summary()

# Loss function: SparseCategoricalCrossentropy (integer labels 0-9)
loss_fn_fc = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=False)

# Optimizer: Adam
optimizer_fc = tf.keras.optimizers.Adam(learning_rate=1e-3)

# Metric histories
fc_train_loss_history = []
fc_val_loss_history = []
fc_train_acc_history = []
fc_val_acc_history = []

# Number of epochs for training the FC network
epochs_fc = 10

# ===============================================
# 3. Training + validation loop for FC network
# ===============================================

for epoch in range(1, epochs_fc + 1):
    print(f"\n=== [FC Network] Epoch {epoch}/{epochs_fc} ===")

    # ---------- Training phase ----------
    train_losses = []
    train_accuracies = []

    for step, (x_batch, y_batch) in enumerate(train_ds_fc):
        with tf.GradientTape() as tape:
            # Forward pass
            probs = fc_model(x_batch, training=True)
            # Compute loss
            loss_value = loss_fn_fc(y_batch, probs)

        # Compute gradients and update weights
        grads = tape.gradient(loss_value, fc_model.trainable_variables)
        optimizer_fc.apply_gradients(zip(grads, fc_model.trainable_variables))

        # Compute accuracy
        acc = accuracy_from_probs(probs, y_batch)

        train_losses.append(loss_value.numpy())
        train_accuracies.append(acc.numpy())

        if step % 100 == 0:
            print(f"  Step {step:03d} - Batch loss: {loss_value:.4f}, accuracy: {acc:.4f}")

    # Aggregate training metrics
    epoch_train_loss = np.mean(train_losses)
    epoch_train_acc = np.mean(train_accuracies)

    # ---------- Validation phase ----------
    val_losses = []
    val_accuracies = []

    for x_batch_val, y_batch_val in val_ds_fc:
        probs_val = fc_model(x_batch_val, training=False)
        val_loss_value = loss_fn_fc(y_batch_val, probs_val)
        val_acc = accuracy_from_probs(probs_val, y_batch_val)

        val_losses.append(val_loss_value.numpy())
        val_accuracies.append(val_acc.numpy())

    epoch_val_loss = np.mean(val_losses)
    epoch_val_acc = np.mean(val_accuracies)

    # Store history
    fc_train_loss_history.append(epoch_train_loss)
    fc_val_loss_history.append(epoch_val_loss)
    fc_train_acc_history.append(epoch_train_acc)
    fc_val_acc_history.append(epoch_val_acc)

    print(
        f"Epoch {epoch}: "
        f"Train loss = {epoch_train_loss:.4f}, Train acc = {epoch_train_acc:.4f} | "
        f"Val loss = {epoch_val_loss:.4f}, Val acc = {epoch_val_acc:.4f}"
    )

# ===============================================
# 4. Plot FC training/validation curves and show example prediction
# ===============================================

epochs_range_fc = range(1, epochs_fc + 1)

plt.figure()
plt.plot(epochs_range_fc, fc_train_loss_history, label="Train Loss")
plt.plot(epochs_range_fc, fc_val_loss_history, label="Val Loss")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("Fully Connected Network - Loss per Epoch")
plt.legend()
plt.grid(True)
plt.show()

plt.figure()
plt.plot(epochs_range_fc, fc_train_acc_history, label="Train Accuracy")
plt.plot(epochs_range_fc, fc_val_acc_history, label="Val Accuracy")
plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.title("Fully Connected Network - Accuracy per Epoch")
plt.legend()
plt.grid(True)
plt.show()

# Example prediction from the FC network
sample_index = 0
sample_image_flat = x_test_flat[sample_index : sample_index + 1]  # shape (1, 784)
sample_image = x_test[sample_index]  # shape (28, 28)
true_label = y_test[sample_index]

probs = fc_model(sample_image_flat, training=False).numpy().squeeze()
predicted_class = np.argmax(probs)

print("True label:", true_label)
print("Predicted class (FC network):", predicted_class)
print("Predicted probabilities:", probs)

plt.figure()
plt.imshow(sample_image, cmap="gray")
plt.title(f"FC Network Prediction: {predicted_class} (True: {true_label})")
plt.axis("off")
plt.show()

# ===============================================
# 5. CNN model definition
#    Architecture outline:
#    Input -> Conv -> MaxPool -> Conv -> Dropout
#          -> MaxPool -> Conv -> MaxPool -> Dense -> Dense -> Output
# ===============================================

cnn_model = tf.keras.Sequential(
    [
        tf.keras.layers.Input(shape=(28, 28, 1), name="input_image"),

        # Block 1: Conv -> MaxPool
        tf.keras.layers.Conv2D(32, kernel_size=(3, 3), activation="relu", name="conv_1"),
        tf.keras.layers.MaxPooling2D(pool_size=(2, 2), name="maxpool_1"),

        # Block 2: Conv -> Dropout -> MaxPool
        tf.keras.layers.Conv2D(64, kernel_size=(3, 3), activation="relu", name="conv_2"),
        tf.keras.layers.Dropout(0.25, name="dropout_1"),
        tf.keras.layers.MaxPooling2D(pool_size=(2, 2), name="maxpool_2"),

        # Block 3: Conv -> MaxPool
        tf.keras.layers.Conv2D(128, kernel_size=(3, 3), activation="relu", name="conv_3"),
        tf.keras.layers.MaxPooling2D(pool_size=(2, 2), name="maxpool_3"),

        # Flatten and two fully connected layers
        tf.keras.layers.Flatten(name="flatten"),
        tf.keras.layers.Dense(128, activation="relu", name="dense_1"),
        tf.keras.layers.Dense(64, activation="relu", name="dense_2"),

        # Output layer with Softmax over 10 classes
        tf.keras.layers.Dense(10, activation="softmax", name="output_softmax"),
    ],
    name="CNN_FASHION_MNIST",
)

cnn_model.summary()

# Loss function and optimizer (same form as FC network)
loss_fn_cnn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=False)
optimizer_cnn = tf.keras.optimizers.Adam(learning_rate=1e-3)

# Metric histories
cnn_train_loss_history = []
cnn_val_loss_history = []
cnn_train_acc_history = []
cnn_val_acc_history = []

epochs_cnn = 10

# ===============================================
# 6. Training + validation loop for CNN
# ===============================================

for epoch in range(1, epochs_cnn + 1):
    print(f"\n=== [CNN] Epoch {epoch}/{epochs_cnn} ===")

    # ---------- Training phase ----------
    train_losses = []
    train_accuracies = []

    for step, (x_batch, y_batch) in enumerate(train_ds_cnn):
        with tf.GradientTape() as tape:
            probs = cnn_model(x_batch, training=True)
            loss_value = loss_fn_cnn(y_batch, probs)

        grads = tape.gradient(loss_value, cnn_model.trainable_variables)
        optimizer_cnn.apply_gradients(zip(grads, cnn_model.trainable_variables))

        acc = accuracy_from_probs(probs, y_batch)

        train_losses.append(loss_value.numpy())
        train_accuracies.append(acc.numpy())

        if step % 100 == 0:
            print(f"  Step {step:03d} - Batch loss: {loss_value:.4f}, accuracy: {acc:.4f}")

    epoch_train_loss = np.mean(train_losses)
    epoch_train_acc = np.mean(train_accuracies)

    # ---------- Validation phase ----------
    val_losses = []
    val_accuracies = []
    for x_batch_val, y_batch_val in val_ds_cnn:
        probs_val = cnn_model(x_batch_val, training=False)
        val_loss_value = loss_fn_cnn(y_batch_val, probs_val)
        val_acc = accuracy_from_probs(probs_val, y_batch_val)

        val_losses.append(val_loss_value.numpy())
        val_accuracies.append(val_acc.numpy())

    epoch_val_loss = np.mean(val_losses)
    epoch_val_acc = np.mean(val_accuracies)

    cnn_train_loss_history.append(epoch_train_loss)
    cnn_val_loss_history.append(epoch_val_loss)
    cnn_train_acc_history.append(epoch_train_acc)
    cnn_val_acc_history.append(epoch_val_acc)

    print(
        f"Epoch {epoch}: "
        f"Train loss = {epoch_train_loss:.4f}, Train acc = {epoch_train_acc:.4f} | "
        f"Val loss = {epoch_val_loss:.4f}, Val acc = {epoch_val_acc:.4f}"
    )

# ===============================================
# 7. Plot CNN training/validation curves and show example prediction
# ===============================================

epochs_range_cnn = range(1, epochs_cnn + 1)

plt.figure()
plt.plot(epochs_range_cnn, cnn_train_loss_history, label="Train Loss")
plt.plot(epochs_range_cnn, cnn_val_loss_history, label="Val Loss")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("CNN - Loss per Epoch")
plt.legend()
plt.grid(True)
plt.show()

plt.figure()
plt.plot(epochs_range_cnn, cnn_train_acc_history, label="Train Accuracy")
plt.plot(epochs_range_cnn, cnn_val_acc_history, label="Val Accuracy")
plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.title("CNN - Accuracy per Epoch")
plt.legend()
plt.grid(True)
plt.show()

# Example prediction from the CNN
sample_index = 1  # different from FC example

sample_image_cnn = x_test_cnn[sample_index : sample_index + 1]  # shape (1, 28, 28, 1)
sample_image_raw = x_test[sample_index]  # shape (28, 28)
true_label_cnn = y_test[sample_index]

probs_cnn = cnn_model(sample_image_cnn, training=False).numpy().squeeze()
predicted_class_cnn = np.argmax(probs_cnn)

print("True label:", true_label_cnn)
print("Predicted class (CNN):", predicted_class_cnn)
print("Predicted probabilities:", probs_cnn)

plt.figure()
plt.imshow(sample_image_raw, cmap="gray")
plt.title(f"CNN Prediction: {predicted_class_cnn} (True: {true_label_cnn})")
plt.axis("off")
plt.show()